function [mdl_svm, incorrectly_classified_svm, accuracy_svm] = svm_model(data_train, data_test, y_label_train , y_label_test)

    template = templateSVM(...
        'KernelFunction', 'polynomial', ...
        'PolynomialOrder', 3, ...
        'KernelScale', 'auto', ...
        'BoxConstraint', 1, ...
        'Standardize', true);
    mdl_svm = fitcecoc(...
        data_train, y_label_train, ...
        'Learners', template, ...
        'Coding', 'onevsall');
    predicted_svm = predict(mdl_svm, data_test);

    incorrectly_classified_svm = sum(predicted_svm ~= y_label_test);
    accuracy_svm = (size(predicted_svm,1)- incorrectly_classified_svm) / size(predicted_svm,1) * 100;

end